apiVersion: v2
name: booking-service
description: A Helm chart for EventSphere Booking Service
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg


