apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-ebs
  namespace: prod
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
  allowAutoIOPSPerGBIncrease: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain




