apiVersion: v2
name: frontend
description: A Helm chart for EventSphere Frontend (React + Nginx)
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.svg


